### ISSUE TITLE
Script says that I don't have OpenCL installed when the package name contains driver version

### ISSUE THREAD

**Issue by talentlessguy** [Ashark/davinci-resolve-checker#3]
Here's what I have:

```sh
➜ prime ./davinci-resolve-checker.py
DaVinci Resolve checker 1.2.1
You do not have opencl-nvidia package. Install it, otherwise you could not use D.R. Even if you are planning to use cuda, opencl-nvidia will be installed as its dependency.

➜ yay -Qs opencl-nvidia
local/opencl-nvidia-440xx 440.100-1
    OpenCL implemention for NVIDIA
```

Shouldn't it check for the `opencl-nvidia-<version>xx` as well?

**Comment by Ashark** [comment]
Does DR actually work with this version? I do not have an old nvidia gpu, so I could not test it myself.
If yes, then I will also check for that opencl-nvidia-<version>xx package.

**Comment by Ashark** [comment]
@bandithedoge I cannot reproduce. Can you run 1.3.1 version? I added detected configuration to output.

**Comment by talentlessguy** [comment]
@Ashark still happens on 1.3.1

```sh
➜ yay -Qs opencl-nvidia
local/opencl-nvidia-450xx 450.66-1
    OpenCL implemention for NVIDIA

/tmp via 🐍 v3.8.5 
➜ prime python davinci-resolve-checker.py 
DaVinci Resolve checker 1.3.1
Your configuration:
Chassis: laptop
Installed OpenCL drivers: intel-compute-runtime opencl-mesa opencl-nvidia-450xx
Presented GPUs:
        UHD Graphics 620 driver: i915
        GP107M [GeForce GTX 1050 Mobile] driver: nvidia
OpenGL vendor string: NVIDIA Corporation
You do not have opencl-nvidia package. Install it, otherwise you could not use D.R. Even if you are planning to use cuda, opencl-nvidia will be installed as its dependency.
```

**Comment by Ashark** [comment]
@talentlessguy you are talking about opencl-nvidia-450xx, but @bandithedoge was talking about opencl-nvidia.

**Comment by bandithedoge** [comment]
Unfortunately I don't have the card anymore so I can't test it.

**Comment by creepinson** [comment]
I just got the same problem
```
DaVinci Resolve checker 1.3.2
Your configuration:
Chassis: desktop
Installed OpenCL drivers: opencl-nvidia-455xx
Presented GPUs:
        GP107 [GeForce GTX 1050 Ti] driver: nouveau
OpenGL vendor string: nouveau
You do not have opencl-nvidia package. Install it, otherwise you could not use D.R. Even if you are planning to use cuda, opencl-nvidia will be installed as its dependency.
```

**Comment by bandithedoge** [comment]
> I just got the same problem
> 
> ```
> DaVinci Resolve checker 1.3.2
> Your configuration:
> Chassis: desktop
> Installed OpenCL drivers: opencl-nvidia-455xx
> Presented GPUs:
>         GP107 [GeForce GTX 1050 Ti] driver: nouveau
> OpenGL vendor string: nouveau
> You do not have opencl-nvidia package. Install it, otherwise you could not use D.R. Even if you are planning to use cuda, opencl-nvidia will be installed as its dependency.
> ```
> 
> Edit: idk how to select the right driver in manjaro kde but i think its using the wrong one for some reason

Yes, this is definitely the wrong one. You should use the proprietary `nvidia` driver instead of the free `nouveau` driver.

**Comment by imsofi** [comment]
Does this program hardcode check for the `opencl-nvidia` package? Im running tkg-dev drivers and still get the error of opencl not beeing installed.
```
DaVinci Resolve checker 1.4.1
Chassis type: desktop
Installed OpenCL drivers: chaotic-nvidia-dev-opencl-tkg lib32-chaotic-nvidia-dev-opencl-tkg
Presented GPUs:
	TU106 [GeForce RTX 2060 Rev. A] (kernel driver in use: nvidia)
OpenGL vendor string: NVIDIA Corporation

You do not have opencl-nvidia package. Install it, otherwise you could not use DR Even if you are planning to use cuda, opencl-nvidia will be installed as its dependency.
```

**Comment by Ashark** [comment]
@imsofi Currently, yes: https://github.com/Ashark/davinci-resolve-checker/blob/ea69a3540975a17c3bfa04909592532d034d1b05/davinci-resolve-checker.py#L106
What is chaotic-nvidia-dev-opencl-tkg? There is no such package in aur or official packages. Shouldn't the package provide opencl-nvidia? Have you actually tried to run dr? Is it working?

**Comment by imsofi** [comment]
> What is chaotic-nvidia-dev-opencl-tkg?

`chaotic` means its from the [Chaotic AUR](https://lonewolf.pedrohlc.com/chaotic-aur/), its a generate on-demand repo so you dont have to compile things from the AUR yourself. Also adds extra packages not usually found in the AUR as well.

`nvidia-dev-opencl-tkg` comes from [nvidia-tkg](https://github.com/chaotic-aur/nvidia-tkg), specifically the vulkan dev version. Tkg adds some nice patches ontop of nvidias normal binaries. Most recent big one was the fix for 5.9 kernels before nvidia themselves fixed it.<

> Shouldn't the package provide opencl-nvidia?

Checking the output of `clinfo` yes it does.

@Ashark A simple fix might be to rephrase the error to `you may not have opencl-nvidia installed.` Or maybe trying to use something like `clinfo` itself to check if openCL is installed correctly instead of hardcoding package names.

Thanks for making this script. Installing Davinci Resolve on linux has always been a pain.

**Comment by Ashark** [comment]
> Or maybe trying to use something like clinfo itself to check if openCL is installed correctly instead of hardcoding package names.

No, I cannot do that, because it is possible that user has working output in clinfo, but for example dr crashed (at least previously) when opencl-mesa was installed near opencl-amd, or opencl-nvidia near opencl-amd. So I want to see which exact packages are installed for opencl.

> Checking the output of clinfo yes it does.

Again, I just wanted to rely on arch linux packaging sources, but not on clinfo information. Looking at this [line](https://github.com/chaotic-aur/nvidia-tkg/blob/e0ed7f07c424248d947e35019153e7c7478947b2/PKGBUILD#L779), it seems like you need to install opencl-nvidia-tkg package.

> A simple fix might be to rephrase the error to you may not have opencl-nvidia installed.

You mean, replace "You do not have opencl-nvidia package." to "You do not have opencl-nvidia package or some package which provides it.", right?

> Thanks for making this script. Installing Davinci Resolve on linux has always been a pain.

I am glad this is useful. To be honest, I am really fed up with this shitty guessing and poking of how to make it work. And no any adequate official information on this. Just spend tons and tons of hours to experiment if it will work with some configuration. And even if it crashes at launch, no way to determine why it is happening.

**Comment by imsofi** [comment]
> You mean, replace "You do not have opencl-nvidia package." to "You do not have opencl-nvidia package or some package which provides it.", right?

Yeah exactly that. As `You do not have opencl-nvidia` makes me really doubt if i have opencl-nvidia even if i do trough the `-tkg` version.
